docors/urls.py
#flake8: noqa
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import login, password_reset
from django.contrib.auth.views import password_reset_confirm, password_reset_done
from django.contrib.auth.views import password_reset_complete
from docors import views
from practitioner.sitemap import PractitionerSitemap

sitemaps = {
    'practitioners': PractitionerSitemap,
}

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^adv', views.adv, name='adv'),
    url(r'^social-accounts/', include('allauth.urls')),
    url(r'^', include('docorsauth.urls')),
    url(r'^', include('practitioner.urls')),
    url(r'^', include('practice.urls')),
    url(r'^', include('patients.urls')),
    url(r'^', include('reviews.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',{'post_reset_redirect' : '/password/reset/done/'}, name='password_reset'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/password/done/'}),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^privacy-policy/$', views.policy, name='privacy_policy'),
    url(r'^terms-service/$', views.tos, name='tos'),
    url(r'^user-agreement/$', views.user_agreement, name='user_agreement'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    )
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
        )

docors/forms.py
# flake8: noqa
from django import forms
from django.forms.widgets import Input, HiddenInput
from practitioner.models import Specialization
from practice.models import Area, City

class doctors_form(forms.Form):

	q = forms.CharField(
		max_length=100,
		required=False,
		label="Doctor",
		widget=forms.TextInput(
			attrs={
			'placeholder': 'Doctor Name, Specialty, Condition or Procedure',
			'class':'doc-typeahead'
		}))

class speciality_form(forms.Form):

	spec = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	area = forms.ChoiceField(choices = [(r.id, r.name) for r in Area.objects.filter(city=City.objects.get(name='Lahore'))], label='Area.', required = True)

class advanced_form(forms.Form):

	RADIUS_CHOICES = ((1, '1'), (2, '2'), (5, '5'), (10, '10'), (15, '15'), (20, '20'),)
	DAYS = (('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'),('6', 'Saturday'),('7', 'Sunday'),)

	spec_adv = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	lon = forms.CharField(label='Physical longitude.', widget=forms.HiddenInput(), required=False)
	lat = forms.CharField(label='Physical latitude.', widget=forms.HiddenInput(), required=False)
	radius = forms.ChoiceField(choices = RADIUS_CHOICES, label="Radius (KM)", initial='2', required = True)
	day = forms.ChoiceField(choices = DAYS, label = "Day", initial='1', required = True)

docors/views.py
# flake8: noqa
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from practitioner.models import *
from patients.models import Patient
from practice.models import PracticeLocation
from hitcount.models import HitCount
from django.contrib.contenttypes.models import ContentType

from .utility import *
from docors.forms import *

# Create your views here.

#main page
def index(request):
    data = {'popular_pract':list(),'popular_proc':list(),'popular_practice':list()}
    data['specialities'] = Specialization.objects.order_by('slug')
    contents_types = dict()
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(Practitioner)).order_by('-hits')[:5]:
        data['popular_pract'].append(hc.content_object)
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(Procedure)).order_by('-hits')[:5]:
        data['popular_proc'].append(hc.content_object)
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(PracticeLocation)).order_by('-hits')[:5]:
        data['popular_practice'].append(hc.content_object)

    try:
        patient_data = Patient.patient_objects.patient_details(lambda: request.user if request.user.is_authenticated() else None)
    except Patient.DoesNotExist:
        pass

    data['doc_form'],data['spec_form'],data['adv_form'] = doctors_form(),speciality_form(),advanced_form()

    return render_to_response('index.html', {'data': data}, context_instance=RequestContext(request))

#advance search
def adv(request):
    data = {}
    if request.method == "GET":
        try:
            data['specialities'] = Specialization.objects.order_by('human_name')
            data['cities'] = City.objects.order_by('pk')
        except Specialization.DoesNotExist:
            raise Http404
    return render_to_response('practitioner/advance.html', {'data': data}, context_instance=RequestContext(request))

def policy(request):
    return render_to_response('policy.html', {}, context_instance=RequestContext(request))

def tos(request):
    return render_to_response('tos.html', {}, context_instance=RequestContext(request))

def user_agreement(request):
    return render_to_response('user_agreement.html', {}, context_instance=RequestContext(request))

docors/templates/base.html
{% load i18n %}
<!DOCTYPE html "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

	<head>
		<!-- Start CSS SECTION -->
	    {% load staticfiles %}
	    <meta charset="utf-8">
	    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> -->
	    <!-- ///  page title  /// -->
	    <title>{% block title %}Doctorsinfo.pk | Find a Doctor, Review Doctor, Doctor Ratings{% endblock %}</title>
	    <link rel="shortcut icon" href="{{STATIC_URL}}assets/img/doctorsinfo.ico">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    	<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		<!-- Font Awesome CDN -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		<!-- QTtip CDN CSS -->
		<link rel="stylesheet" href="http://cdn.jsdelivr.net/qtip2/2.2.1/jquery.qtip.min.css">
		<!-- Bootstrap Social Buttons -->
		<link rel="stylesheet" href="{% static 'assets/css/bootstrap-social.css' %}">
		<!-- Style -->
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
		<!-- Custom Style -->
		<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
        <!-- Component Style -->
        <!-- yamm Style -->
        <link rel="stylesheet" href="{% static 'assets/css/yamm.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/select2.min.css' %}">
		<!-- Font Style -->
		<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
		{% block pageSpecificCSS %}{% endblock %}
		{% block fbTags %}
		<meta property="og:title" content="Doctors info. Pakistan - health care informatics."/>
		<meta property="og:description" content="Pakistan's first health information online portal. Find specialist doctors in your area by thier name, specialty, conditions, procedures or clinic name." />
		<meta property="og:url" content="http://doctorsinfo.pk" />
		<meta property="og:image" content="http://doctorsinfo.pk/static/icons/logo.png" />{% endblock %}
		{% block seoTags %}
		<meta name="description" content="Pakistan's first health information online portal. Find specialist doctors in your area by thier name, specialty, conditions, procedures or clinic name." />
		<meta content="specialst doctors in lahore, pediatrics, child specialist, gyne, gynecologist, psychiatrist, neurologist, radiologists, urologist, dermatologist, nephrologist" name="keywords" />
		<meta property="og:site_name" content="Doctors Listing Website" />
		<meta property="fb:app_id" content="753672898036503" />
		<meta property="og:type" content="website" />
		<meta name="google-site-verification" content="4eQap4DygfxsfuocwBZAZxmS3eXhMVhwlo2KQ47S7-Q" />
		<meta property="og:locale" content="en_US" />
		<link href="http://doctorsinfo.pk/" rel="canonical" />{% endblock %}
		{% block reCaptcha %}{% endblock %}
		{% block customStylesheet %}{% endblock %}
		<!-- End CSS SECTION -->
		<!-- JS FILES -->
		<!-- JQUERY JS -->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<!-- BOOTSTRAP JS -->
		<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		<!-- Validator JS -->
		<script type="text/javascript" src="{% static 'assets/js/validator.js' %}"></script>
        <!-- sticky header JS -->
        <script type="text/javascript" src="{% static 'assets/js/jquery.sticky.js' %}"></script>
        <!-- sticky header JS -->
        <script type="text/javascript" src="{% static 'assets/js/custom.js' %}"></script>
        <!-- Form validation jquery -->
        <script type="text/javascript" src="{% static 'assets/js/select2.full.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'assets/js/jquery.form.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
		{% block pageSpecificJS %}{% endblock %}
		<!-- End JS FILES -->
	</head>
	<body class="remove-scroll {% block extraBodyClass %}{% endblock %}">
    	{% include "fragments/header.html" %}
		<div itemscope itemtype="{% block seoItemTags %}{% endblock %}" role="main" class="{% block containerClass %}{% endblock %} page-wrap">
        	{% block content %}{% endblock %}
    	</div>
    	{% include "fragments/footer.html" %}
	</body>
	{% block customScript %}{% endblock %}
    {% include "fragments/google-analytics.html" %}
</html>

docors/templates/index.html
{% extends "base.html" %}
{% block title %}doctorsinfo.pk - find specialist doctors, review doctors and doctor ratings{% endblock %}
{% block home_active %}active{% endblock %}
{% load staticfiles %}
		{% block content %}
		<!-- Start Middle Content -->
		<section class="main-section">
			<div class="color-correction"></div>
			<div class="container">
				<div class="row row-space-75-0">
					<div class="text-center">
						<h2 style="color: #fafafa">Find specialist doctors in your area.</h2>
					</div>
					<div class="text-center" style="color: #fafafa;">
						<span>Know your doctor, better.</span>
					</div>
				</div>
				<div class="row row-space-75-0">
					<div class="col-md-8 col-md-offset-2">
						<div class="sky-tabs sky-tabs-amount-3 sky-tabs-pos-top-justify sky-tabs-anim-slide-up sky-tabs-response-to-icons">
							<input type="radio" name="sky-tabs" checked="" id="find-doctors" class="sky-tab-content-1">
							<label for="find-doctors"><span><span><i class="fa fa-user-md"></i>Find Doctors</span></span></label>
							
							<input type="radio" name="sky-tabs" id="find-speciality" class="sky-tab-content-2">
							<label for="find-speciality"><span><span><i class="fa fa-stethoscope"></i>Specialty</span></span></label>
							
							<input type="radio" name="sky-tabs" id="find-adv" class="sky-tab-content-3">
							<label for="find-adv" class="find-advanced"><span><span><i class="fa fa-cogs"></i>Advanced</span></span></label>
							
							<ul class="custom-sky-tabs-content">
								<li class="sky-tab-content-1">					
									<div class="typography1">
										<form class="sky-form custom-sky-form" role="form" action="{% url 'physican_suggestions' %}" method="GET">
			                            	<fieldset>
			                        			<label class="select">
                                                    <select id="id_search_main" name="q"></select>
			                        			</label>
			                        		</fieldset>
			                            </form>
									</div>
								</li>
								<li class="sky-tab-content-2">
									<div class="typography">
										<form role="form" class="sky-form custom-sky-form" action="{% url 'search_speciality' %}" >
											<fieldset>
												<div class="row">
													<section class="col col-5">
							                        	{{data.spec_form.spec.label}}
							                            <label class="select">
							                            	{{ data.spec_form.spec }}
							                            </label>
							                        </section>
							                        <section class="col col-5">
							                        	{{data.spec_form.area.label}}
							                            <label class="select">
							                            	{{data.spec_form.area}}
							                            </label>
							                        </section>
							                        <section class="col col-2">
								                        	<button type="submit" class="button custom-submit-button"><i class="fa fa-search"></i></button>
							                        </section>
												</div>
											</fieldset>
		                                </form>
									</div>
								</li>
								
								<li class="sky-tab-content-3">
									<div class="typography">
										<form role="form" class="sky-form custom-sky-form" action="{% url 'search_advanced' %}" method="POST">{% csrf_token %}
											<fieldset>
												<div class="row">
													<section class="col col-4">
							                        	{{data.adv_form.spec_adv.label}}
							                            <label class="select">
							                            	{{data.adv_form.spec_adv}}
							                            </label>
							                        </section>
							                        <section class="col col-3">
							                        	{{data.adv_form.radius.label}}
							                        	<label class="select">
							                        		{{data.adv_form.radius}}
							                        		<i></i>
							                        	</label>
							                        </section>
							                        <section class="col col-3">
							                        	{{data.adv_form.day.label}}
							                        	<label class="select">
							                        		{{data.adv_form.day}}
							                        		<i></i>
							                        	</label>
							                        	{{data.adv_form.lat}}{{data.adv_form.lon}}
							                        </section>
							                        <section class="col col-2">
								                        	<button type="submit" class="button custom-submit-button" data-geo="true" data-geoerror="Not possible to get location at the moment. Please try again later" id="adv_search_btn"><i class="fa fa-search"></i></button>
							                        </section>
							                    </div>
							                </fieldset>
							            </form>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="bottom-section">
			<div class="container">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-4 bottom-section-left">
							<div class="row">
								<div class="bottom-section-left-img text-center margin20">
									<img src="{% static 'assets/img/doctor.png' %}" alt="Doctor"/>
								</div>
								<div class="bottom-section-left-heading text-center">
									<h3>Doctors for you</h3>
								</div>
								<div class="bottom-section-left-hr">
									<hr align="center" width="50%">
									<hr align="center" width="50%">
								</div>
								<div class="bottom-section-left-paragraph text-center">
									<ul class="list-unstyled margintop15">
										{% for pract in data.popular_pract %}
                                        {% if pract %}
										<li><a href="/physican/{{pract.slug}}">{{pract}}</a></li>
                                        {% endif %}
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-4 bottom-section-left">
							<div class="row">
								<div class="bottom-section-left-img text-center margin20">
									<img src="{% static 'assets/img/hospital.png' %}" alt="Doctor"/>
								</div>
								<div class="bottom-section-left-heading text-center">
									<h3>Hospital/Clinics For You</h3>
								</div>
								<div class="bottom-section-left-hr">
									<hr align="center" width="50%">
									<hr align="center" width="50%">
								</div>
								<div class="bottom-section-left-paragraph text-center">
									<ul class="list-unstyled margintop15">
										{% for practice in data.popular_practice %}
                                        {% if pract %}
										<li><a href="/{{practice.slug}}-in-PracticeLocation">{{practice}}</a></li>
                                        {% endif %}
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-4 bottom-section-right">
							<div class="row">
								<div class="bottom-section-right-img text-center margin20">
									<img src="{% static 'assets/img/kit.png' %}" alt="Doctor"/>
								</div>
								<div class="bottom-section-right-heading text-center">
									<h3>Medical Treatments For You</h3>
								</div>
								<div class="bottom-section-right-hr">
									<hr align="center" width="50%">
									<hr align="center" width="50%">
								</div>
								<div class="bottom-section-right-paragraph text-center">
									<ul class="list-unstyled margintop15">
										{% for proc in data.popular_proc %}
                                        {% if pract %}
										<li><a href="/{{proc.slug}}-in-Procedure">{{proc}}</a></li>
                                        {% endif %}
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<div class="divide80"></div>
	{% endblock %}
	{% block pageSpecificCSS %}
	<link href="{% static 'assets/css/sky-forms.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/sky-tabs.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'assets/css/sweetalert.css' %}">
	{% endblock %}
	{% block pageSpecificJS %}
		<script src="{% static 'assets/js/sweetalert.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/typeahead.js' %}"></script>
	{% endblock %}

	{% block customScript %}

	<script type="text/javascript">

		$(document).ready(function(){

		    $("#id_spec").select2({placeholder: 'Select Specialty'});
		    $("#id_area").select2({placeholder: 'Select Area'});
		    $("#id_spec_adv").select2({placeholder: 'Select Specialty'});
		    $("#id_radius").select2({placeholder: 'Select Radius'});
		    $("#id_day").select2({placeholder: 'Select Day'});


		    $("#id_spec").select2("val", "");$("#id_area").select2("val", "");$("#id_spec_adv").select2("val", "");$("#id_radius").select2("val", "");$("#id_day").select2("val", "");

            $("#id_search_main").select2({'placeholder': 'Doctor name, Specialty, Condition, Procedure or Hospital/Clinic Name', multiple:true,
                ajax: {
                    url: '{% url "physican_suggestions" %}',
                    dataType: "json",
                    data: function(params) {
                        return {
                            q: params.term,
                        };
                    },
                    processResults: function(data, page) {
                        return {
                            results: data
                        };
                    },
                    cache:true
                },
                minimumInputLength:3,
                maximumSelectionLength:1
            }).on("select2:select",function(e){
                console.log(e.params.data);
                serch_selection(e.params.data);
            });

		});

		function showPosition(position) {
			$("#adv_search_btn").data('geo','false');
		    $("#id_lat").val(position.coords.latitude);
		    $("#id_lon").val(position.coords.longitude);
		}

		function showError(error) {
		    switch(error.code) {
		        case error.PERMISSION_DENIED:
		        	$("#adv_search_btn").data('geoerror','User denied the request for Geolocation.');
		            break;
		        case error.POSITION_UNAVAILABLE:
		        	$("#adv_search_btn").data('geoerror','User Position unavailable');
		            break;
		        case error.TIMEOUT:
		        	$("#adv_search_btn").data('geoerror','Not possible to get location at the moment. Please try again later');
		            break;
		        case error.UNKNOWN_ERROR:
		            $("#adv_search_btn").data('geoerror','Not possible to get location at the moment. Please try again later');
		            break;
		    }
		}

		$(".find-advanced").click(function(e){
			if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(showPosition,showError);
		    } else {
		        $("#adv_search_btn").data('geoerror','Geolocation is not supported by this browser.');
		    }
		});

		$("#adv_search_btn").click(function(e){
			if($("#adv_search_btn").data('geo') == true){
				e.preventDefault();
				swal({title: "GeoLocation Error!",text: $("#adv_search_btn").data('geoerror'),type: "warning"});
			}
		});

		$(".city_name").on("click",function(){
			var city_slug = $(this).data("cityslug");
			$.ajax({
				type: "GET",
				url: "{% url 'get_areas' %}",
				data: {'city':city_slug,'header_city':true},
				success: function(data){
					$("#curr_city").text(city_slug);
					$("#curr_city").data("cityslug",city_slug);
					local_areas = Array();
					for(i=0;i<data['areas'].length;i++){
						local_areas.push(data['areas'][i]);
					}
					$(".area_typeahead").typeahead('destroy');
					$(".area_typeahead").typeahead('destroy');
					$(".area_typeahead").typeahead({
						minLength:0,
						hint: true,
						highlight: true
					}, {
						source: substringMatcher(local_areas),
						limit:100
					})
					.blur(function(){
						if(local_areas.indexOf($(this).typeahead('val')) === -1)
							$(this).typeahead('val','');
					});
				}
			});
		});

        function serch_selection(data){
            console.log("coming to change");
            if(data.type == 'Practitioner'){
                window.location = '/physican/'+data.slug;
            }else{
                window.location = '{% url "physican_search" %}?q='+data.slug+'&search.type='+data.type+'&loc='+$("#curr_city").data('cityslug');
            }
        }
	</script>

	{% endblock %}

docors/templates/policy.html
{% extends 'base.html' %}
{% block title %}doctorsinfo.pk - Privacy Policy{% endblock %}

{% block content %}
	<div class="breadcrumb-wrap">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h4>Privacy Policy</h4>
                </div>
                <div class="col-sm-6 hidden-xs text-right">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li>Privacy Policy</li>
                    </ol>
                </div>
            </div>
        </div>
    </div><!--breadcrumbs-->
    <div class="divide40"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 margin20">
                <h3 class="heading">1. INFORMATION WE COLLECT</h3>
                <p>We collect the following types of information.</p>
                <p>Information you provide us directly:</p>
                <ul>
                	<li>Your full name, e-mail address and password when you register for a doctorsinfo.pk account.</li>
                	<li>Profile information that you provide for your user profile (e.g., gender, phone number, year of birth).</li>
                	<li>Your current city from your IP address.</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 margin20">
                <h3 class="heading">2. WHY DO WE COLLECT THAT INFORMATION OF YOURS</h3>
                <ul>
                	<li><strong>Full name</strong> (To help other patients have a sense of security, when you left a feedback about a doctor or ask a question on discussion forum.)</li>
                	<li><strong>email-address</strong> (To help you recover your account, in-case you have lost access to your account and approve your activity at <strong>doctorsinfo.pk</strong> )</li>
                	<li><strong>Gender</strong> (To personalize the content on our site according to your gender.)</li>
                	<li><strong>Phone number</strong> (To inform you about any changes in practice information for your favorite Practitioners.)</li>
                	<li><strong>Year of Birth</strong> (To personalize the content on our site according to your age group.)</li>
                	<li><strong>City</strong> (To show you doctors relevant to your city.)</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 margin20">
                <h3 class="heading">3. HOW WE USE YOUR INFORMATION</h3>
                <ul>
                	<li>help you efficiently access your personal information after you sign in</li>
					<li>remember information so you will not have to re-enter it during your visit or the next time you visit the Service.</li>
					<li>provide personalized content and information to you and others, which could include on-line ads.</li>
					<li>provide, improve, test, and monitor the effectiveness of our Service</li>
					<li>monitor metrics such as total number of visitors, traffic, and demographic patterns</li>
					<li>diagnose or fix technical faults.</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 margin20">
                <h3 class="heading">4. SHARING OF YOUR INFORMATION</h3>
                <ul>
                	<li>We will not rent or sell your information to third parties outside doctorsinfo.pk without your consent, except as noted in this Policy.</li>
					<li>If we sell or otherwise transfer part or the whole of doctorsinfo.pk or our assets to another organization (e.g., in the course of a transaction like a merger, acquisition, bankruptcy, dissolution, liquidation), your information such as full name and email address, User Content and any other information collected through the Service may be among the items sold or transferred. You will continue to own your User Content. The buyer or transferee will have to honor the commitments we have made in this Privacy Policy.</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 margin20">
                <h3 class="heading">5. YOUR CHOICES ABOUT YOUR PERSONAL INFORMATION</h3>
                <ul>
                	<li>Update your account at any time by logging in and changing your profile settings.</li>
					<li>Un-subscribe from emails from us by clicking on the "un-subscribe link" provided in such emails.</li>
					<li>Following termination or deactivation of your account, <u><em><strong>doctorsinfo.pk</strong></em></u> may retain information (including your profile information) and User Content for a reasonable time for backup, archival, and/or audit purposes.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="divide40"></div>
{% endblock %}