docors/urls.py
#flake8: noqa
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import login, password_reset
from django.contrib.auth.views import password_reset_confirm, password_reset_done
from django.contrib.auth.views import password_reset_complete
from docors import views
from practitioner.sitemap import PractitionerSitemap

sitemaps = {
    'practitioners': PractitionerSitemap,
}

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^adv', views.adv, name='adv'),
    url(r'^social-accounts/', include('allauth.urls')),
    url(r'^', include('docorsauth.urls')),
    url(r'^', include('practitioner.urls')),
    url(r'^', include('practice.urls')),
    url(r'^', include('patients.urls')),
    url(r'^', include('reviews.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',{'post_reset_redirect' : '/password/reset/done/'}, name='password_reset'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/password/done/'}),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^privacy-policy/$', views.policy, name='privacy_policy'),
    url(r'^terms-service/$', views.tos, name='tos'),
    url(r'^user-agreement/$', views.user_agreement, name='user_agreement'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    )
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
        )

patients/urls.py
from django.conf.urls import patterns, url
from patients import views

urlpatterns = patterns('',
	url(r'^patient/physican', views.physican_patient, name='patient_physican'),
	url(r'^patient/specialities', views.specialities_patient, name='patient_specialty'),
	url(r'^patient/reviews', views.reviews_patient, name='patient_reviews'),
	url(r'^patient/profile', views.profile_patient, name='patient_profile'),
	url(r'^patient/subscribe', views.subscribe_patient, name='subscribe'),
	url(r'^WhoIsMyDoctor', views.educate_patient, name='WhoIsMyDoctor'),
	url(r'^favt_pract', views.favt_pract, name='add_favt_pract'),
	url(r'^patient/preferences/$', views.preferences_patient, name='patient_preferences'),
)

docorsauth/models.py
#flake8: noqa
import datetime
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.utils.crypto import get_random_string
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

from .managers import EmailConfirmationManager

# Here the magic happens enjoy.
# Custom User model

class docorsUserManager(BaseUserManager):
	def create_user(self, email, full_name, password=None):
		if not email:
			raise ValueError("User must provide an email address")

		user = self.model(email=self.normalize_email(email),full_name=full_name)
		if password:
			user.set_password(password)
		else:
			user.set_unusable_password()
		user.save(using=self._db)
		return user

	def create_superuser(self, email, full_name, password):
		user = self.create_user(email, password=password, full_name=full_name)
		user.is_admin = True
		user.is_active = True
		user.save(using=self._db)
		return user

class docorsUser(AbstractBaseUser):
	# this will be the identifier for the user model
	GENDER_CHOICES = ( ('M', 'Male'),('F', 'Female'), ('', 'Prefer not to disclose'))
	YEAR_CHOICES = []
	for r in range(1930, (datetime.datetime.now().year-12)):
		YEAR_CHOICES.append((r,r))
	
	email = models.EmailField(verbose_name="email address", max_length=255, unique=True)
	full_name = models.CharField(max_length=100)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='', blank=True)
	year_of_birth = models.PositiveSmallIntegerField(
		'Year of Birth',
		choices=YEAR_CHOICES,
		default=1930,
		blank=True
	)

	modified = models.DateTimeField(auto_now=True)
	is_active = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)

	objects = docorsUserManager()
	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ["full_name"]

	class Meta:
		verbose_name_plural = "Registered Users"

	def __str__(self):
		return self.full_name

	def get_full_name(self):
		return self.full_name

	def get_short_name(self):
		return self.email

	def has_perm(self, perm, obj=None):
		#THis will always return True
		return True

	def has_module_perms(self, app_label):
		#Check if the user has permission to a specific app mentioned by app_label
		#This will in most cases return True
		return True

	def email_user(self, subject, message, from_email=None, **kwargs):
		"""Send email to the user"""
		send_mail(subject,message,from_email,[self.email], **kwargs)

	@property
	def is_staff(self):
		#Check if the user is member of staff.
		#The simple answer is if the user is admin then yes
		return self.is_admin

class EmailConfirmation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name=_('user'))
    email = models.EmailField(unique=True,max_length=254,verbose_name=_('e-mail address'))
    created = models.DateTimeField(verbose_name=_('created'),default=timezone.now)
    sent = models.DateTimeField(verbose_name=_('sent'), null=True)
    key = models.CharField(verbose_name=_('key'), max_length=64, unique=True)
    verified = models.BooleanField(verbose_name=_('verified'), default=False)

    objects = EmailConfirmationManager()

    class Meta:
        verbose_name = _("email confirmation")
        verbose_name_plural = _("email confirmations")

    def __str__(self):
        return "confirmation for %s" % self.user

    @classmethod
    def create(cls, user):
        key = get_random_string(64).lower()
        return cls._default_manager.create(user=user, email=user.email, key=key)

    def key_expired(self):
        expiration_date = self.sent + datetime.timedelta(days=7)
        return expiration_date <= timezone.now()
    key_expired.boolean = True

    def email_sent(self):
    	self.sent = timezone.now()
    	self.save()
    	return self.sent

    def confirm_activation(self):
    	data = dict()
        if not self.key_expired() and not self.user.is_active:
            user = self.user
            user.is_active = True
            user.save()
            self.verified = True
            self.save()
            data['success'] = True
        elif self.key_expired():
        	data['success'] = False
        	data['error_message'] = 'Activation Key Expired'
        elif self.user.is_active:
        	data['success'] = False
        	data['error_message'] = 'Email address already verified'
        return data

patients/models.py
# flake8: noqa
from django.db import models
from practitioner.models import Specialization, Practitioner
from practice.models import City
from docorsauth.models import docorsUser
from django.core.validators import MaxValueValidator, MinValueValidator


#customManager
class SubscriptionManager(models.Manager):

    def subscription_email_details(self, email, practitioner):
        return super(SubscriptionManager, self).filter(email=email, practitioner=practitioner)

    def subscription_mobile_details(self, mobile, practitioner):
        return super(SubscriptionManager, self).filter(cell_number=mobile, practitioner=practitioner)

    def subscription_both_details(self, email, mobile, practitioner):
        return super(SubscriptionManager, self).filter(email=email, cell_number=mobile, practitioner=practitioner)


class Subscription(models.Model):
    cell_number = models.CharField(max_length=20,null=True, blank=True)
    email = models.EmailField(max_length=35, blank=True, null=True)
    practitioner = models.ForeignKey(Practitioner)


    objects = models.Manager()
    subscription_objects = SubscriptionManager()

    def __str__(self):
        return self.practitioner.name

    class Meta:
        verbose_name_plural = 'Subscriptions'


#customManager
class PatientManager(models.Manager):

    def patient_details(self, email):
        return super(PatientManager, self).get(email=email)

    def registered_patient(self, email):
        return super(PatientManager, self).filter(email=email)

    def get_city(self, email):
        return super(PatientManager, self).get(email=email).city

    def remove_physican(self, email, practitioner):
        patient = super(PatientManager, self).get(email=email)
        patient.favt_practitioner.remove(practitioner)
        return True


class Patient(docorsUser):

    cell_number = models.BigIntegerField(
        unique=True, null=True, blank=True,
        validators=[
            MaxValueValidator(
                3500000000,
                message="Please enter a valid mobile phone number e.g. "
                "03001234567"),
            MinValueValidator(
                3000000000,
                message="Please enter a valid mobile phone number e.g. "
                "03001234567")],
        help_text='Mobile phone number e.g. 03001234567'
    )
    interested_specialities = models.ManyToManyField(Specialization, blank=True)
    favt_practitioner = models.ManyToManyField(Practitioner, blank=True)
    city = models.ForeignKey(City, default=1)
    email_alerts = models.BooleanField(default=True)

    objects = models.Manager()
    patient_objects = PatientManager()

    class Meta:
        verbose_name_plural = 'Patients'

    def patient_name(self):
        return self.full_name

    def __str__(self):
        return self.email

docors/forms.py
# flake8: noqa
from django import forms
from django.forms.widgets import Input, HiddenInput
from practitioner.models import Specialization
from practice.models import Area, City

class doctors_form(forms.Form):

	q = forms.CharField(
		max_length=100,
		required=False,
		label="Doctor",
		widget=forms.TextInput(
			attrs={
			'placeholder': 'Doctor Name, Specialty, Condition or Procedure',
			'class':'doc-typeahead'
		}))

class speciality_form(forms.Form):

	spec = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	area = forms.ChoiceField(choices = [(r.id, r.name) for r in Area.objects.filter(city=City.objects.get(name='Lahore'))], label='Area.', required = True)

class advanced_form(forms.Form):

	RADIUS_CHOICES = ((1, '1'), (2, '2'), (5, '5'), (10, '10'), (15, '15'), (20, '20'),)
	DAYS = (('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'),('6', 'Saturday'),('7', 'Sunday'),)

	spec_adv = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	lon = forms.CharField(label='Physical longitude.', widget=forms.HiddenInput(), required=False)
	lat = forms.CharField(label='Physical latitude.', widget=forms.HiddenInput(), required=False)
	radius = forms.ChoiceField(choices = RADIUS_CHOICES, label="Radius (KM)", initial='2', required = True)
	day = forms.ChoiceField(choices = DAYS, label = "Day", initial='1', required = True)

patients/forms.py
from django import forms
from patients.models import Patient
from django.utils.translation import ugettext_lazy as _

class CreatePatient(forms.ModelForm):

    error_messages = {
        'duplicate_email': _("A user with that email already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }

    password1 = forms.CharField(label=_('Create a Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_('Confirm Password'), widget=forms.PasswordInput, help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = Patient
        fields = ['email','full_name']

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            Patient.objects.get(email=email)
        except Patient.DoesNotExist:
            return email
        raise forms.ValidationError(self.error_messages['duplicate_email'], code='duplicate_email',)

    def clean_password2(self):
        #you dare enter my chambers filthy and uncleaned, you shall be punished you weak human
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        #behold my creation. Feast your eyes with my greatness.
        user = super(CreatePatient, self).save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user

class InterestedSpecForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = ['interested_specialities']

class PatientProfileForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = ['full_name','year_of_birth','cell_number','city']

docors/views.py
# flake8: noqa
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from practitioner.models import *
from patients.models import Patient
from practice.models import PracticeLocation
from hitcount.models import HitCount
from django.contrib.contenttypes.models import ContentType

from .utility import *
from docors.forms import *

# Create your views here.

#main page
def index(request):
    data = {'popular_pract':list(),'popular_proc':list(),'popular_practice':list()}
    data['specialities'] = Specialization.objects.order_by('slug')
    contents_types = dict()
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(Practitioner)).order_by('-hits')[:5]:
        data['popular_pract'].append(hc.content_object)
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(Procedure)).order_by('-hits')[:5]:
        data['popular_proc'].append(hc.content_object)
    for hc in HitCount.objects.filter(content_type=ContentType.objects.get_for_model(PracticeLocation)).order_by('-hits')[:5]:
        data['popular_practice'].append(hc.content_object)

    try:
        patient_data = Patient.patient_objects.patient_details(lambda: request.user if request.user.is_authenticated() else None)
    except Patient.DoesNotExist:
        pass

    data['doc_form'],data['spec_form'],data['adv_form'] = doctors_form(),speciality_form(),advanced_form()

    return render_to_response('index.html', {'data': data}, context_instance=RequestContext(request))

#advance search
def adv(request):
    data = {}
    if request.method == "GET":
        try:
            data['specialities'] = Specialization.objects.order_by('human_name')
            data['cities'] = City.objects.order_by('pk')
        except Specialization.DoesNotExist:
            raise Http404
    return render_to_response('practitioner/advance.html', {'data': data}, context_instance=RequestContext(request))

def policy(request):
    return render_to_response('policy.html', {}, context_instance=RequestContext(request))

def tos(request):
    return render_to_response('tos.html', {}, context_instance=RequestContext(request))

def user_agreement(request):
    return render_to_response('user_agreement.html', {}, context_instance=RequestContext(request))

docors/templates/patients/acc_preferences.html
{% extends 'patients/dashboard_base.html' %}
{% block dashboard_content %}
<div class="col-sm-12">
    <h3 class="heading">Preferences and Settings</h3>
</div>
<div id="email_password_panel" class="col-md-12 sky-form-login-register v2">
    <form action="" method="" class="sky-form">
        <h3 class="text-center">Email and Password</h3>
        <fieldset>
            <section>
                <label class="label">Currently logged in as : {{sticky_data.user.email}}</label>
            </section>
            <section>
                <label class="label">Password : ********</label>
            </section>
		</fieldset>
        <fieldset>
            <footer>
                <div class="row">
                    <button id="change_password_btn" type="button" class="button">Change Password</button>
                </div>
            </footer>
        </fieldset>
	</form>
</div>
<div id="change_password_panel" class="col-md-12 sky-form-login-register v2">
    <form action="" method="POST" class="sky-form">
        {% csrf_token %}
        <h3 class="text-center">Change Password</h3>
		<input type="hidden" name="type_" value="change_password">
        <fieldset>
            <section>
                <label class="label">Current Password</label>
                <label class="input">
					<input type="password" id="id_currentpassword" name="currentpassword">
                </label>
            </section>
            <section>
                <label class="label">New Password</label>
                <label class="input">
					<input type="password" id="id_password1" name="password1">
                </label>
            </section>
            <section>
                <label class="label">Confirm Password</label>
                <label class="input">
					<input type="password" id="id_password2" name="password2">
                </label>
            </section>
        </fieldset>
        <fieldset>
            <footer>
				<div class="row">
				    <button type="submit" class="button">Save Changes</button>
    				<button id="change_password_cancel" type="button" class="button">Cancel</button>
                </div>
            </footer>
        </fieldset>
	</form>
</div>
<div class="divide40 clear"></div>
<div class="col-md-12 sky-form-login-register v2">
    <form action="" method="POST" class="sky-form">
        {% csrf_token %}
		<input type="hidden" name="type_" value="change_preferences">
        <h3 class="text-center">EMAIL PREFERENCES</h3>
        <fieldset>
            <section>
                <label class="checkbox">
					<input type="checkbox" name="preference_checkbox form-control" id="id_preferences" selected>
                    <i></i>
                    Send me relevent, personalized information to help me make better healthcare desicions.
				</label>
            </section>
        </fieldset>
        <fieldset>
            <footer>
                <div class="row">
                    <button type="submit" class="button">Update Preference</button>
                </div>
            </footer>
        </fieldset>
	</form>
</div>
{% endblock %}

{% load staticfiles %}
{% block pageSpecificCSS %}
<link href="{% static 'assets/css/sky-forms.css' %}" rel="stylesheet">
{% endblock %}


{% block customScript %}
	<script type="text/javascript">
		$(document).ready(function(){
			$("#change_password_panel").hide();
		});
		$("#change_password_btn").click(function(){
			$("#change_password_panel").fadeIn();
			$("#email_password_panel").hide();
		});
		$("#change_password_cancel").click(function(){
			$("#change_password_panel").hide();
			$("#email_password_panel").show();
		});
	</script>
{% endblock %}

docors/templates/patients/dashboard_base.html
{% extends 'base.html' %}
{% block header_name %}{{sticky_data.user.full_name}}{% endblock %}
{% block title %}{{sticky_data.user.full_name}} | Profile{% endblock %}
{% block dashboard_profile_link %}#{% endblock %}
{% block content %}
<div class="breadcrumb-wrap breadcrumb-light" style="background-color:#000;">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h4>{{ profile_form.full_name.value }}</h4>
            </div>
            <div class="col-sm-6 hidden-xs text-right">
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li>Profile</li>
                </ol>
            </div>
        </div>
    </div>
</div><!--breadcrumb light-->
<div class="divide80"></div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar-box margin40">
                <h4>Dashboard</h4>
                <ul class="list-unstyled cat-list">
                    <li><a href="{% url 'patient_physican' %}">Doctors</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="{% url 'patient_specialty' %}">Interested Specialities</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="{% url 'patient_reviews' %}">Reviews</a><i class="fa fa-angle-right"></i></li>
                </ul>
            </div>
            <div class="sidebar-box margin40">
                <h4>Account Settings</h4>
                <ul class="list-unstyled cat-list">
                    <li><a href="{% url 'patient_profile' %}">Profile</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="{% url 'patient_preferences' %}">Preferences</a><i class="fa fa-angle-right"></i></li>
                    <li><a href="/accounts/logout">Logout</a><i class="fa fa-angle-right"></i></li>
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            {% block dashboard_content %}{% endblock %}
        </div>
    </div>
</div>
<div class="divide80"></div>
{% endblock %}

docors/templates/patients/educate.html
{% extends "registration/base.html" %}
{% block title %}Who is my Doctor ?| www.doctorsinfo.pk{% endblock %}
{% block loggedInUser %}
{% if data.user.is_authenticated %}
<div id="head">
  <a href="{% url 'patient' %}" class="anchor-link"><i class="fa fa-user fa-1x marg-r"></i>{{data.user.username}}</a>
</div>
{% endif %}
{% endblock %}
{% block containerClass %}container{% endblock %}
{% block content %}
<div class="ui-grid-a">
	<div class="ui-block-a">
		<div class="ui-bar ui-bar-a">
			<h3>Which doctor, should i consult ?</h3>
		</div>
		<p>
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		</p>
	</div>
	<div class="ui-block-b">
		<div class="ui-bar ui-bar-a">
			<h3>Which doctor, should i consult ?</h3>
		</div>
		<p>
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
		</p>
	</div>
</div>
{% endblock %}
<div data-role="footer" style="overflow:hidden;">
	<h4 style="text-align:center;">Doctors info. Pakistan</h4>
	<div data-role="navbar">
		<ul>
		<li><a href="{% url 'registration' %}"><i class="fa fa-list-alt fa-1x"></i>get listed as a Doctor!</a></li>
        <li><a href="{% url 'WhoIsMyDoctor' %}"><i class="fa fa-lightbulb-o fa-1x"></i>Know your doctor</a></li>
        <li><a href="mailto:doctorsinfo.pk@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i>Contact Us</a></li>
        <li><a href="https://www.facebook.com/doctorsinfo.pk" target="_blank"><i class="fa fa-facebook fa-1x"></i>facebook</a></li>
        <li><a href="http://twitter.com/doctorsinfo_pk" target="_blank"><i class="fa fa-twitter fa-1x"></i>twitter</a></li>
        <li><a href="https://plus.google.com/+DoctorsinfoPk" rel="publisher" target="_blank"><i class="fa fa-google-plus fa-1x"></i>google+</a></li>
        <li class="extraLinks"><a class="mezino" href="http://mezino.com"><img src="{{ STATIC_URL }}icons/mezino.png"></a>
		</ul>
	</div>
</div>

docors/templates/patients/interested_specialities.html
{% extends 'patients/dashboard_base.html' %}
{% load staticfiles %}
{% block dashboard_content %}
<div class="col-sm-12">
    <h3 class="heading">Interested Specialities</h3>
</div>
<div class="col-md-12 main-doctor-holder">
    <div class="additional-amenities">
    {% for spec in data.int_specialities %}
        <span class="available"><i class="fa fa-check-square"></i> {{spec.human_name}}</span>
    {% empty %}
    </div>
    <div class="col-md-12 text-center error-text">
        <h1 class="error-digit"><i class="fa fa-heartbeat"></i></h1>
        <h2>Opps, your speciality list is empty.</h2>
    </div>
    {% endfor %}
    <div class="divide40"></div>
    <div class="col-md-12 text-center error-text">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#specModal">Update Specialities</button>
    </div>
</div>
<div class="modal fade" id="specModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="POST" class="sky-form">
                {% csrf_token %}
            <div class="modal-header">
                <h4 class="modal-title">Change Interested Specialities</h4>
            </div>
            <div class="modal-body text-center">
                        <label>Interested Specialities</label>
                            {{form.interested_specialities}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block customScript %}
<script type="text/javascript">
    $(document).ready(function(){
            $("#id_interested_specialities").css("width","100%");
            $("#id_interested_specialities").select2({
                'placeholder':'Select Specialities'
            });
    });
</script>
{% endblock %}

docors/templates/patients/profile.html
{% extends 'patients/dashboard_base.html' %}
{% block dashboard_content %}
<div class="col-sm-12">
    <h3 class="heading">Profile</h3>
</div>
<div class="col-md-12 sky-form-login-register v2">
    {% if profile_form.errors %}
    <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        {{ profile_form.errors.as_ul}}
    </div>
    {% endif %}
    <form action="" method="POST" class="sky-form">
        {% csrf_token %}
        <fieldset>
            <div class="row">
                <section>
                    <label class="label">Full Name</label>
                    <label class="input">
                        {{profile_form.full_name}}
                    </label>
                </section>
            </div>
            <div class="row">
                <section>
                    <label class="label">Year of Birth</label>
                    <label class="select">
                        {{profile_form.year_of_birth}}
                    </label>
                </section>
            </div>
            <div class="row">
                <section>
                    <label class="label">Cell Number</label>
                    <label class="input">
                        {{profile_form.cell_number}}
                    </label>
                </section>
            </div>
            <div class="row">
                <section>
                    <label class="label">City</label>
                    <label class="select">
                        {{profile_form.city}}
                    </label>
                </section>
            </div>
        </fieldset>
        <fieldset>
            <footer>
                <div class="row">
                    <button type="submit" class="button">Update</button>
                </div>
            </footer>
        </fieldset>
    </form>
</div>
{% endblock %}

{% load staticfiles %}
{% block pageSpecificCSS %}
<link href="{% static 'assets/css/sky-forms.css' %}" rel="stylesheet">
{% endblock %}

{% block customScript %}
<script type="text/javascript">
    $("#id_year_of_birth").select2({'placeholder':'Select birth Year'});
    $("#id_city").select2({'placeholder':'Select City'});

    function reset_values(){
      $("#id_firstname").val("{{data.patient.user.first_name}}");
      $("#id_lastname").val("{{data.patient.user.last_name}}");
      $("#id_age option[value='{{data.patient.age_group}}']").prop('selected',true);
      $("#id_gender option[value='{{data.patient.gender}}']").prop('selected',true);
      $("#id_number").val("{{data.patient.cell_number}}")
    }
</script>
{% endblock %}