docors/urls.py
#flake8: noqa
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth.views import login, password_reset
from django.contrib.auth.views import password_reset_confirm, password_reset_done
from django.contrib.auth.views import password_reset_complete
from docors import views
from practitioner.sitemap import PractitionerSitemap

sitemaps = {
    'practitioners': PractitionerSitemap,
}

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^adv', views.adv, name='adv'),
    url(r'^social-accounts/', include('allauth.urls')),
    url(r'^', include('docorsauth.urls')),
    url(r'^', include('practitioner.urls')),
    url(r'^', include('practice.urls')),
    url(r'^', include('patients.urls')),
    url(r'^', include('reviews.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',{'post_reset_redirect' : '/password/reset/done/'}, name='password_reset'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/password/done/'}),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^privacy-policy/$', views.policy, name='privacy_policy'),
    url(r'^terms-service/$', views.tos, name='tos'),
    url(r'^user-agreement/$', views.user_agreement, name='user_agreement'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
    )
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes':True}),
        )

practitioner/urls.py
from django.conf.urls import patterns, url
from practitioner import views

urlpatterns = patterns('',
                       # Search Related urls
                       url(
                           r'^physican/suggestions/$',
                           views.suggestions_practitioner,
                           name='physican_suggestions'
                       ),
                       url(
                           r'^physican/search/$',
                           views.search_practitioner,
                           name='physican_search'
                       ),
                       url(
                           r'^(?P<condition>[a-z-]+)-treatment-in-(?P<location>[A-Za-z-]+)$',
                           views.results_condition,
                           name='condition_results'
                       ),
                       url(
                           r'^(?P<procedure>[a-z-]+)-procedure-in-(?P<location>[A-Za-z-]+)$',
                           views.results_procedure,
                           name='procedure_results'
                       ),
                       url(
                           r'^(?P<specialty_fellowship>[a-z-]+)-in-(?P<location>[A-Za-z-]+)$',
                           views.results_specialty_fellowship,
                           name='specialty_fellowship_results'
                       ),
                       url(
                           r'^(?P<practice>[a-z-]+)-(?P<location>[A-Za-z-]+)$',
                           views.results_practice,
                           name='practice_results'
                       ),
                       # Physican Page urls
                       url(
                           r'^physican/(?P<slug>[\w-]+)/claim/$',
                           views.claim_practitioner,
                           name='claim_practitioner'
                       ),
                       url(
                           r'^physican/(?P<slug>[\w-]+)/update/info/$',
                           views.update_info_practitioner,
                           name='update_info_practitioner'
                       ),
                       url(
                           r'^physican/profile/$',
                           views.profile_practitioner,
                           name='practitioner_profile'
                       ),
                       url(
                           r'^physican/(?P<slug>[\w-]+)/review/$',
                           views.review_practitioner,
                           name='practitioner_review'
                       ),
                       # Physican Registration related urls
                       url(
                           r'^physican/registration',
                           views.registration_practitioner,
                           name='practitioner_registration'
                       ),
                       url(
                           r'^physican/get-cond-proc-ajax/$',
                           views.get_cond_proc_ajax,
                           name='get_condition_procedure'
                       ),
                       url(
                           r'^physican/get-practice-names-ajax/$',
                           views.get_practice_names_ajax,
                           name='get_practice_names'
                       ),
                       url(
                           r'^physican/get-practice-details-ajax/$',
                           views.get_practice_details_ajax,
                           name='get_practice_details'
                       ),
                       url(
                           r'^physican/get-region-details-ajax/$',
                           views.get_region_details_ajax,
                           name='get_region_details'
                       ),
                       )

practitioner/models.py
from django.db import models
from django.db.models import Q
from autoslug import AutoSlugField
from sorl.thumbnail import ImageField
from docorsauth.models import docorsUser
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _


class SpecializationManager(models.Manager):
    def spec_slug(self, slug):
        return super(SpecializationManager, self).get(slug=slug)

    def get_default_id(self):
        return super(SpecializationManager, self).all()[0].id

    def spec_human_name(self, name):
        return super(SpecializationManager, self).get(human_name=name)

    def get_spec_by_region(self, region):
        return super(
            SpecializationManager,
            self
        ).filter(
            Q(training_region__icontains=region) | Q(training_region='all')
        ).values('id', 'name')


class Specialization(models.Model):
    REGION = [
        ('all', 'All'),
        ('pak', 'Asia'),
        ('eur', 'Europe/UK'),
        ('usa', 'United States'),
        ('pak_eur', 'Pakistan/Europe'),
        ('pak_usa', 'Pakistan/USA'),
        ('eur_usa', 'Europe/USA'),
    ]

    name = models.CharField(max_length=100)
    human_name = models.CharField(max_length=100, null=True)
    SEO_name = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True, blank=True)
    training_region = models.CharField(
        max_length=10,
        null=True,
        choices=REGION)
    slug = AutoSlugField(populate_from='name', unique=True)

    objects = models.Manager()
    spec_objects = SpecializationManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Specialties"
        ordering = ('name',)


class FellowshipManager(models.Manager):
    def spec_slug(self, slug):
        return super(FellowshipManager, self).get(slug=slug)


class Fellowship(models.Model):
    name = models.CharField(max_length=100)
    human_name = models.CharField(max_length=100, null=True)
    specialization = models.ForeignKey(Specialization)
    description = models.TextField(null=True, blank=True)
    slug = AutoSlugField(populate_from='name', unique=True)

    objects = models.Manager()
    fellow_objects = FellowshipManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Fellowships"
        ordering = ('name',)


class ConditionManager(models.Manager):
    def get_slug(self, name):
        return super(ConditionManager, self).get(name=name)

    def get_conditions(self, specialization):
        return super(ConditionManager, self).filter(
            specialization=specialization)

    def get_specialization(self, condition):
        return super(ConditionManager, self).get(name=condition)

    def get_condition(self, pk):
        return super(ConditionManager, self).get(pk=pk)


class Condition(models.Model):
    name = models.CharField(max_length=100)
    specialization = models.ForeignKey(Specialization)
    fellowship = models.ForeignKey(Fellowship, null=True, blank=True)
    slug = AutoSlugField(populate_from='name', unique=True)

    objects = models.Manager()
    condition_objects = ConditionManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Conditions'
        ordering = ('name',)


class ProcedureManager(models.Manager):
    def get_slug(self, name):
        return super(ProcedureManager, self).get(name=name)

    def get_procedures(self, specialization):
        return super(ProcedureManager, self).filter(
            specialization=specialization)

    def get_specialization(self, procedure):
        return super(ProcedureManager, self).get(name=procedure)

    def get_procedure(self, pk):
        return super(ProcedureManager, self).get(pk=pk)


class Procedure(models.Model):
    name = models.CharField(max_length=100)
    specialization = models.ForeignKey(Specialization)
    fellowship = models.ForeignKey(Fellowship, null=True, blank=True)
    slug = AutoSlugField(populate_from='name', unique=True)

    objects = models.Manager()
    procedure_objects = ProcedureManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Procedures'
        ordering = ('name',)


class DegreeManager(models.Manager):
    def get_degree(self, name):
        return super(DegreeManager, self).get(name=name)


class Degree(models.Model):
    name = models.CharField(max_length=50)
    points = models.PositiveSmallIntegerField(default=0)
    color_code = models.CharField(max_length=10, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)

    # Manager
    objects = models.Manager()
    degree_objects = DegreeManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Degrees"
        ordering = ('name',)


class PractitionerManager(models.Manager):

    def practitioner_slug(self, slug):
        return super(PractitionerManager, self).get(slug=slug)

    def practitioner_suggest(self, name):
        return super(
            PractitionerManager,
            self
        ).filter(
            full_name__icontains=name,
            is_active=True
        ).values_list('name', flat=True)

    def practitioner_by_practice(self, name):
        return super(
            PractitionerManager,
            self
        ).filter(
            full_name__icontains=name,
            is_active=True
        )


class Practitioner(docorsUser):
    PHYSICIAN_CHOICES = [
        ('0', 'General Physician'),
        ('1', 'Trainee'),
        ('2', 'Specialist'),
    ]

    physician_type = models.CharField(
        max_length=1,
        choices=PHYSICIAN_CHOICES,
        null=True
    )
    photo = ImageField(upload_to='practitioner/', blank=True, null=True)
    experience = models.PositiveIntegerField(
        help_text="Number of years",
        default=0
    )
    achievements = models.TextField(null=True, blank=True)
    message = models.CharField(max_length=140, null=True, blank=True)
    degrees = models.ManyToManyField(Degree)

    # specialities
    specialty = models.ForeignKey(Specialization, null=True, blank=True)
    fellowship = models.ManyToManyField(Fellowship, blank=True)
    completion_year = models.PositiveIntegerField(
        "Fellowship expected in year.",
        default=0
    )
    conditions = models.ManyToManyField(Condition, blank=True)
    procedures = models.ManyToManyField(Procedure, blank=True)

    slug = AutoSlugField(populate_from='full_name', unique=True)
    education_marks = models.PositiveIntegerField(default=0)
    recommendation = models.PositiveIntegerField(default=0)
    not_recommended = models.PositiveIntegerField(default=0)
    review_rating = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        default=0.0
    )

    # Manager
    objects = models.Manager()
    prac_objects = PractitionerManager()

    def __unicode__(self):
        return self.full_name

    class Meta:
        verbose_name_plural = "Practitioners"
        ordering = ('-modified',)

    def get_absolute_url(self):
        return reverse('practitioner', kwargs={'slug': self.slug})


class ClaimManager(models.Manager):
    def get_claim(self, email):
        return super(ClaimManager, self).get(email=email)


class Claim(models.Model):
    practitioner = models.ForeignKey(Practitioner)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        help_text=_("Verification email will be sent at this address. So please \
            ensure you enter correct email"))
    pmdc_no = models.CharField(max_length=20)
    photo = ImageField(
        upload_to='practitioner/claim/photo/',
        blank=True,
        null=True,
        help_text=_("Please provide a passport size photograph of yours to help \
            in the verification process."))
    prescription_photo = ImageField(
        upload_to='practitioner/claim/prescription_photo/',
        blank=True,
        null=True,
        help_text=_("Please provide a passport size photograph of yours to help \
            in the verification process."))
    current_status = models.BooleanField(default=False)

    objects = models.Manager()
    claim_objects = ClaimManager()

    class Meta:
        verbose_name_plural = "Practitioner Claims"
        ordering = ('email',)

    def __unicode__(self):
        return self.pmdc_no


class UpdateInfoManager(models.Manager):
    def get_updates(self, practitioner):
        return super(UpdateInfoManager, self).filter(practitioner=practitioner)


class UpdateInfo(models.Model):
    UPDATE_CHOICES = [
        ('1', 'Physican Type'),
        ('2', 'Experience'),
        ('3', 'Achievements'),
        ('4', 'Degree'),
        ('5', 'Speciality'),
        ('6', 'Fellowship'),
        ('7', 'Completion Year'),
        ('8', 'Conditions'),
        ('9', 'Procedures')
    ]

    practitioner = models.ForeignKey(Practitioner)
    ip = models.CharField(
        verbose_name='IP address or Email',
        max_length=255,
        null=True,
        blank=True
    )
    incorrect_info = models.CharField(
        max_length=1,
        choices=UPDATE_CHOICES,
        null=True
    )
    correct_info = models.CharField(max_length=150)
    comments = models.CharField(max_length=150, null=True, blank=True)
    approved = models.BooleanField(default=False)

    objects = models.Manager()
    updateinfo_objects = UpdateInfoManager()

    class Meta:
        verbose_name = "Update Info"
        ordering = ('practitioner',)

    def __unicode__(self):
        return self.correct_info

docors/forms.py
# flake8: noqa
from django import forms
from django.forms.widgets import Input, HiddenInput
from practitioner.models import Specialization
from practice.models import Area, City

class doctors_form(forms.Form):

	q = forms.CharField(
		max_length=100,
		required=False,
		label="Doctor",
		widget=forms.TextInput(
			attrs={
			'placeholder': 'Doctor Name, Specialty, Condition or Procedure',
			'class':'doc-typeahead'
		}))

class speciality_form(forms.Form):

	spec = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	area = forms.ChoiceField(choices = [(r.id, r.name) for r in Area.objects.filter(city=City.objects.get(name='Lahore'))], label='Area.', required = True)

class advanced_form(forms.Form):

	RADIUS_CHOICES = ((1, '1'), (2, '2'), (5, '5'), (10, '10'), (15, '15'), (20, '20'),)
	DAYS = (('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'),('6', 'Saturday'),('7', 'Sunday'),)

	spec_adv = forms.ChoiceField(choices = [(r.id, r.human_name) for r in Specialization.objects.order_by('name')], label='Specialty.', required = True)
	lon = forms.CharField(label='Physical longitude.', widget=forms.HiddenInput(), required=False)
	lat = forms.CharField(label='Physical latitude.', widget=forms.HiddenInput(), required=False)
	radius = forms.ChoiceField(choices = RADIUS_CHOICES, label="Radius (KM)", initial='2', required = True)
	day = forms.ChoiceField(choices = DAYS, label = "Day", initial='1', required = True)

docors/templates/practitioner/claim.html
{% extends "base.html" %}
{% load staticfiles %}
{% block pageSpecificCSS %}<link href="{% static 'assets/css/sky-forms.css' %}" rel="stylesheet">{% endblock %}
{% block content %}
<div class="breadcrumb-wrap breadcrumb-light" style="background-color:#000;">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h4>Claim Your Profile</h4>
            </div>
            <div class="col-sm-6 hidden-xs text-right">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li>Claim Profile</li>
                </ol>
            </div>
        </div>
    </div>
</div><!--breadcrumb light-->
<div class="divide60"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3 sky-form-login-register">
            <div class="margin40">
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert">&times;</a>
                        {{ form.non_field_errors.as_ul }}   
                    </div>
                {% endif %}
            	<form class="sky-form" role="form" action="" method="POST" data-toggle="validator">{% csrf_token %}
                    <h3 class="text-center"><a href="{% url 'practitioner' slug=practitioner.slug %}">{{practitioner}}</a></h3>
                    <h3 class="text-center">Please Provide the following information.</h3>

                    <fieldset>					
                        <section>
                            <div class="row">
                                <label class="label col col-4">{{form.email.label}}</label>
                                <div class="col col-8">
                                    <label class="input">
                                        <i class="icon-append fa fa-user"></i>
                                        {{form.email}}
                                    </label>
                                </div>
                            </div>
                        </section>

                        <section>
                            <div class="row">
                                <label class="label col col-4">{{form.pmdc_no.label}}</label>
                                <div class="col col-8">
                                    <label class="input">
                                        <i class="icon-append fa fa-lock"></i>
                                        {{form.pmdc_no}}
                                    </label>
                                </div>
                            </div>
                        </section>
                    </fieldset>
                    <footer class="text-right">
                        <button type="submit" class="btn btn-theme-bg btn-lg">Claim</button>
                    </footer>
                </form>			
            </div><!--login form wrap end-->
        </div>
    </div>
</div>
{% endblock %}

docors/templates/practitioner/claim_pending.html
{% extends "base.html" %}
{% block title %}Claim Request Pending | Doctors Info. Pakistan{% endblock %}
{% block content %}
<div class="divide80"></div>
<div class="container">
	<h1>Claim Request Recieved</h1>
	<p class="text-success">Our team will now process your claim request and one of our members will soon be in contact with you.</p>
	<p class="text-success">You will also be informed through the email address you provided upon the successful completion of the claim request.</p>
	<p class="text-primary"><a href="/">Go back to homepage</a></p>
</div>
<div class="divide80"></div>
{% endblock %}

docors/templates/practitioner/edit.html
{% extends 'base.html' %}
{% block title %}doctorsinfo.pk - {{data.practitioner.full_name}}{% endblock %}
{% block content %}
<div class="divide60"></div>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			{% if error_occured %}
			<div class="alert alert-danger text-center">
                An Error Occured during account creation process. Please try again.
            </div>
            {% endif %}
        </div>
        <div class="col-sm-12 sky-form-login-register v2">
            <div class="margin40">

                <form action="" method="POST" role="form" id="sky-form-doctors" class="sky-form">{% csrf_token %}

                	<h3 class="text-center"><a href="{% url 'practitioner' slug=data.practitioner.slug %}">{{data.practitioner.full_name}}</a></h3>

                    <h3 class="text-center">Edit Your Profile</h3>

                    <fieldset>
                    	<div class="row">
	                        <section class="col col-6">
	                        	<label>Condtions</label>
	                            <label class="select">
	                                {{form.conditions}}
	                                <i></i>
	                            </label>
	                        </section>
	                        <section class="col col-6">
	                        	<label>Procedures</label>
	                            <label class="select">
	                                {{form.procedures}}
	                                <i></i>
	                            </label>
	                        </section>
	                    </div>
	                    <div class="row">
	                        <section class="col col-6">
	                        	<label>Achivements</label>
	                            <label class="textarea">
	                                {{form.achievements}}
	                            </label>
	                        </section>
	                        <section class="col col-6">
	                        	<label>Message</label>
	                            <label class="input">
	                                <i class="icon-append fa fa-envelope-o"></i>
	                                {{form.message}}
	                                <b class="tooltip tooltip-bottom-right">Message for your patients</b>
	                            </label>
	                        </section>
	                    </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% load staticfiles %}
{% block pageSpecificCSS %}
<link href="{% static 'assets/css/sky-forms.css' %}" rel="stylesheet">
{% endblock %}

{% block pageSpecificJS %}
<script type="text/javascript" src="{% static 'assets/js/autosize.min.js' %}"></script>
{% endblock %}

{% block customScript %}
<script type="text/javascript">

	$(document).ready(function(){
		$("#id_conditions,#id_procedures").select2();
		autosize($('textarea'));
	});

</script>
{% endblock %}

docors/templates/practitioner/results.html
{% extends "base.html" %}
{% load staticfiles %}
{% load hitcount_tags %}

{% load humanize %}
{% block seoItemTags %}http://schema.org/Physician{% endblock %}
{% block content %}

<div class="search-area">
    <div class="container">
            <div class="col-sm-5">
                <h5>Search Again : </h5>
                <select id="id_search_main" class="full-width" name="search_main" multiple="multiple"></select>
            </div>
    </div>
</div>
{% insert_hit_count_js_variables for data.ob%}
<div class="container">
    <div class="divide20"></div>
    <div class="row no-margin-sides margin-bottom">
        <div class="col-md-12">
            <span class="h2">We have found {{data.results_count}} <span class="text-blue">{{data.results_header}}</span></span>
        </div>
     </div>
</div>
{% if data.searchType == "practice" %}
<div class="container">
    <div class="col-md-8">
        <div class="event-box" style="overflow:hidden;">
            <h3 class="colored-text">{{data.ob.name}}</h3>
            <img src="{% static 'assets/img/hospital.jpg' %}" class="img-responsive" width="120" height="150" style="float:left;margin-right:10px;" alt>
            <p style="margin:0;">{{data.ob.clinic_address}}</p>
            <p style="margin:0;">{{data.ob.area}}</p>
            <p style="margin:0;">{{data.ob.contact_number}}</p>
            <span class="label label-primary" style="float:left;">share</span>
        </div>
    </div>
</div>
{% endif %}
<div class="search-area">
    <div class="container">
      <div class="col-md-12">
          <ul class="list-inline">
            <li>Sort By >> </li>
            <li><strong>Best Match</strong></li>
            <li>|</li>
            <li>CheckUp Fee</li>
            <li>|</li>
            <li>Practitioner Type</li>
            <li>|</li>
            <li>Distance</li>
          </ul>
      </div>
    </div>
</div>
<div class="divide40"></div>
<div class="container">
    <div class="row no-margin-sides margin-bottom">
      <div class="col-md-12">
        {% for onePractitioner in data.practice %}
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title col-md-4" style="padding-top:18px;"><a href="{% url 'practitioner' slug=onePractitioner.practitioner.slug %}">{{onePractitioner.practitioner.full_name}}</a></h3>
                <div class="col-md-4 speciality-label"><span class="label label-primary" style="margin-left:15px;">{{onePractitioner.practitioner.specialty.name}}</span></div>
                <div class="box-tools col-md-4">
                    <button class="btn btn-flat margin pull-right" style="border-radius:1.2em">
                        {{ onePractitioner.practitioner.review_rating}} <i class="fa fa-star text-yellow"></i> 
                    </button>
                </div>
            </div>
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tbody>
                        <tr><th><i class="fa fa-mars text-blue"></i> Gender</th><th><i class="fa fa-heart text-red"></i> Experience</th><th><i class="fa fa-map-marker text-blue"></i> Location</th><th><i class="fa fa-money text-green"></i> Checkup Fee</th><th><i class="fa fa-mobile text-navy"></i> Contact</th></tr>
                        <tr><td>{{onePractitioner.practitioner.get_gender_display}}</td><td>{{onePractitioner.practitioner.experience}} Years</td><td>{{onePractitioner.practice_location.area.name}}, {{onePractitioner.practice_location.area.city.name}}</td><td><small>Rs</small> <b>{{onePractitioner.fee.amount}}</b></td><td>{{onePractitioner.practice_location.contact_number}}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <a href="{% url 'practitioner' slug=onePractitioner.practitioner.slug %}"><span class="btn btn-flat bg-navy pull-right">Visit Profile >> </span></a>
            </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}
{% block pageSpecificCSS %}<link rel="stylesheet" href="{% static 'assets/css/components.css' %}">{% endblock %}
k
{% block pageSpecificJS %}<script src="{% static 'assets/js/hitcount-jquery.js' %}"></script>{% endblock %}

{% block customScript %}
<script type="text/javascript">
            $("#id_search_main").select2({'placeholder':'Doctor, Condition, Procedure',multiple:true,
                ajax: {
                    url: '{% url "physican_suggestions" %}',
                    dataType: "json",
                    data: function(params) {
                        return {
                            q: params.term,
                        };
                    },
                    processResults: function(data, page) {
                        return {
                            results: data
                        };
                    },
                    cache:true
                },
                minimumInputLength:3,
                maximumSelectionLength:1
            }).on("select2:select",function(e){
                console.log(e.params.data);
                serch_selection(e.params.data);
            });
        function serch_selection(data){
            if(data.type == 'Practitioner'){
                window.location = '/physican/'+data.slug;
            }else{
                window.location = '{% url "physican_search" %}?q='+data.slug+'&search.type='+data.type+'&loc='+$("#curr_city").data('cityslug');
            }
        }
</script>
{% endblock %}

docors/templates/practitioner/review_success.html
{% extends "base.html" %}
{% block title %}Review Submitted| Doctors Info. Pakistan{% endblock %}
{% block content %}
<div class="divide80"></div>
<div class="container">
	<h1>Review Submitted Successfully</h1>
    <p class="text-success">You have recently reviewd <a href="{% url 'practitioner' slug=new_review.practitioner.slug%}">{{new_review.practitioner.full_name}}</a>. If you have written some comment then it will be checked by our team for approval.</p>
	<p class="text-success">You will also be informed through the email address once your comment gets approved.</p>
	<p class="text-primary"><a href="/">Go back to homepage</a></p>
</div>
<div class="divide80"></div>
{% endblock %}

docors/templates/practitioner/success.html
{% extends "base.html" %}
{% block title %}Registration Complete | Doctors Info. Pakistan{% endblock %}
{% block content %}
<div class="divide80"></div>
<div class="container">
	<h1>Registration Successfull</h1>
	<p class="text-success">Account Status : <strong>Pending</strong>.</p>
	<p class="text-success">Your request has been recieved Sucessfully, Once your provided info. is reviewed and updated on our site, we will inform you at your provided email:<br> {{email}}<br><br>Thanks.</strong></p>
	<p class="text-primary"><a href="/">Go back to homepage</a></p>
</div>
<div class="divide80"></div>
{% endblock %}

docors/templates/practitioner/updateinfo_pending.html
{% extends "base.html" %}
{% block title %}Update Info Request Pending | Doctors Info. Pakistan{% endblock %}
{% block content %}
<div class="divide80"></div>
<div class="container">
	<h1>Update Info Request Recieved</h1>
	<p class="text-success">We appreciate your effort to help us make information on doctorsinfo authentic. Our team will now process the information provided by you and will check with the practitioner <a href="{% url 'practitioner' slug=info.practitioner.slug %}">{{info.practitioner}}</a> to validate the information.</p>
	<p class="text-primary"><a href="/">Go back to homepage</a></p>
</div>
<div class="divide80"></div>
{% endblock %}